title: Yishun Secondary School
url: https://yishunsec.moe.edu.sg
favicon: /images/yss_logo.png
colors:
  primary-color: "#2034b0"
  secondary-color: "#febd0e"
  media-colors:
    - title: media-color-one
      color: "#252161"
    - title: media-color-two
      color: "#252161"
    - title: media-color-three
      color: "#252161"
    - title: media-color-four
      color: "#252161"
    - title: media-color-five
      color: "#252161"
description: Yishun Secondary School is a co-educational government secondary
  school in Yishun, Singapore. Located at 4 Yishun Street 71, YSS is the first
  school to establish the Applied Learning Programme in Sonic Arts.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d51fzsfg5iatl.amplifyapp.com
prod: https://master.d51fzsfg5iatl.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: yss
